#!/bin/sh
set -ex

NAME="$1"
URL="$2"

echo "Backing up $NAME ($URL)..."

REPO="$CACHE_LOCATION/$NAME"
ARCHIVE="$ARCHIVE_LOCATION/$NAME.zip"

mkdir -p "$REPO"
cd "$REPO"

git clone "$URL" . || true
git fetch -f --prune --prune-tags

MASTER="$(git symbolic-ref --short HEAD)"
HEADHASH="$(git rev-parse HEAD)"
UPSTREAMHASH="$(git rev-parse $MASTER@{upstream})"

if [ "$HEADHASH" != "$UPSTREAMHASH" ]; then
    git clean -fdx
    git reset --hard "$MASTER@{upstream}"

    zip -FS --latest-time -q -r "$ARCHIVE" .

    echo "Backed up $NAME"
else
    echo "No changes in $NAME"
fi
